export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ---- R4 semantic tokens (source of truth: src/styles.css) ---- */
        "gb-canvas": "rgb(var(--gb-canvas) / <alpha-value>)",
        "gb-sidebar": "rgb(var(--gb-sidebar) / <alpha-value>)",
        "gb-surface-1": "rgb(var(--gb-surface-1) / <alpha-value>)",
        "gb-surface-2": "rgb(var(--gb-surface-2) / <alpha-value>)",
        "gb-text-primary": "rgb(var(--gb-text-primary) / <alpha-value>)",
        "gb-text-muted": "rgb(var(--gb-text-muted) / <alpha-value>)",
        "gb-text-disabled": "rgb(var(--gb-text-disabled) / <alpha-value>)",
        "gb-accent-fg": "rgb(var(--gb-accent-fg) / <alpha-value>)",
        "gb-accent-text": "rgb(var(--gb-accent-text) / <alpha-value>)",
        "gb-focus": "rgb(var(--gb-focus) / <alpha-value>)",
        "gb-success": "rgb(var(--gb-success) / <alpha-value>)",
        "gb-success-text": "rgb(var(--gb-success-text) / <alpha-value>)",
        "gb-warning": "rgb(var(--gb-warning) / <alpha-value>)",
        "gb-warning-text": "rgb(var(--gb-warning-text) / <alpha-value>)",
        "gb-danger": "rgb(var(--gb-danger) / <alpha-value>)",
        "gb-danger-text": "rgb(var(--gb-danger-text) / <alpha-value>)",
        "gb-info": "rgb(var(--gb-info) / <alpha-value>)",
        "gb-info-text": "rgb(var(--gb-info-text) / <alpha-value>)",
        /* Border tiers are consumed via the .gb-border-{hairline,control,
           emphasized} utility classes in styles.css, which encode the
           per-theme tier alpha — a tailwind color key cannot express that. */
        /* ---- Legacy aliases (kept; resolve through CSS var chains) ---- */
        "gb-bg": "rgb(var(--gb-bg) / <alpha-value>)",
        "gb-bg-secondary": "rgb(var(--gb-bg-secondary) / <alpha-value>)",
        "gb-surface": "rgb(var(--gb-surface) / <alpha-value>)",
        "gb-surface-hover": "rgb(var(--gb-surface-hover) / <alpha-value>)",
        "gb-surface-solid": "rgb(var(--gb-surface-solid) / <alpha-value>)",
        "gb-border": "rgb(var(--gb-border) / <alpha-value>)",
        "gb-text": "rgb(var(--gb-text) / <alpha-value>)",
        "gb-text-secondary": "rgb(var(--gb-text-secondary) / <alpha-value>)",
        "gb-muted": "rgb(var(--gb-muted) / <alpha-value>)",
        "gb-accent": "rgb(var(--gb-accent) / <alpha-value>)",
        "gb-brand": "rgb(var(--gb-brand) / <alpha-value>)",
        "gb-green": "rgb(var(--gb-green) / <alpha-value>)",
        "gb-yellow": "rgb(var(--gb-yellow) / <alpha-value>)",
        "gb-red": "rgb(var(--gb-red) / <alpha-value>)",
        "gb-activitybar": "rgb(var(--gb-activitybar) / <alpha-value>)",
        "gb-activitybar-fg": "rgb(var(--gb-activitybar-fg) / <alpha-value>)",
        "gb-statusbar": "rgb(var(--gb-statusbar) / <alpha-value>)",
        "gb-tab-inactive": "rgb(var(--gb-tab-inactive) / <alpha-value>)",
      },
      borderRadius: {
        "gb-sm": "var(--gb-radius-sm)",
        "gb-md": "var(--gb-radius-md)",
        "gb-lg": "var(--gb-radius-lg)",
      },
      boxShadow: {
        "gb-low": "var(--gb-elevation-low)",
        "gb-medium": "var(--gb-elevation-medium)",
        "gb-modal": "var(--gb-elevation-modal)",
      },
      transitionDuration: {
        "gb-fast": "140ms",
        "gb-normal": "220ms",
        "gb-deliberate": "320ms",
      },
      transitionTimingFunction: {
        gb: "cubic-bezier(0.2, 0, 0, 1)",
      },
      fontSize: {
        "gb-xs": ["var(--gb-font-xs)", { lineHeight: "1.4" }],
        "gb-sm": ["var(--gb-font-sm)", { lineHeight: "1.4" }],
        "gb-md": ["var(--gb-font-md)", { lineHeight: "1.45" }],
        "gb-lg": ["var(--gb-font-lg)", { lineHeight: "1.35" }],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
